set(include_files
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Attribute.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5DataSet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5DataSpace.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5DataType.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Easy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Exception.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5File.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5FileDriver.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Group.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5PropertyList.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Reference.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Selection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Utility.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/H5Version.hpp.in
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Annotate_traits.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Annotate_traits_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Attribute_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5ConverterEigen_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Converter_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5DataSet_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Dataspace_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5DataType_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Exception_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5FileDriver_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5File_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Iterables_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Node_traits.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Node_traits_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Object_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5PropertyList_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5ReadWrite_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Reference_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Selection_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Slice_traits.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Slice_traits_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5Utils.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/bits/H5_definitions.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_Eigen.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_misc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_opencv.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_public.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_scalar.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_vector.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/h5gt/h5easy_bits/H5Easy_xtensor.hpp
  )
